### ISSUE TITLE
Issue with interuppted update check

### ISSUE THREAD

**Issue by trumpy81** [cowboy/synology-update-plex#17] opened 2020-06-17 16:46 UTC
I received this in my inbox last night.

```
Dear user,

Task Scheduler has completed a scheduled task.

Task: Update Plex
Start time: Wed, 17 Jun 2020 23:00:02 GMT
Stop time: Wed, 17 Jun 2020 23:00:12 GMT
Current status: 5 (Interrupted)
Standard output/error:
Checking for a Plex Media Server update...

[ Enabling Plex Pass releases ]
Found Plex Token

[ Retrieving version data ]
Available version: null
Installed version: 1.19.4.2935-79e214ead

New version available!

[ Finding release ]
jq: error (at <stdin>:1): Cannot iterate over null (null)

Done, with errors!


>From DiskStation
```
I am not sure what the interruption was exactly, but your script did not appear to handle the error as I would expect with a nice output message.

I ran the script manually a short while ago and had no issues, everything worked as expected :)

Just thought you should know.

**Comment by cowboy** [comment] 2020-06-17 16:59
That's really interesting. The script has a lot of error handling, but there are some errors that I never expected would be possible. I'm going to close this issue for now, but if someone else reports something similar, I'll dig a bit deeper. Thanks for reporting!

**Comment by cowboy** [comment] 2020-06-18 14:29
FWIW, I got the _exact_ same error last night. I'm going to do a little more logging on my end to see if I can figure out what's going on.

**Comment by cowboy** [comment] 2020-06-18 15:53
I've created an alternate version of the script with a null check and some more debugging. Feel free to try it out! https://github.com/cowboy/synology-update-plex/pull/18

**Comment by mlemieux77** [comment] 2020-09-25 19:38
i did get that on my ds918+ with dsm 7 with plex pass switch

i did change the volume* in the file

https://drive.google.com/file/d/1BhhyfkwJ_XnARNKj3fwqZ0lxSKbV393q/view?usp=sharing

thanks :)

**Comment by cowboy** [comment] 2020-12-13 18:27
Closing this since I haven't been able to reproduce the error. If it happens again, hopefully the additional debugging I've added will enlighten me :)

**Closed as completed by cowboy** 2020-12-13 18:27 UTC
